/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as RSlugRouteImport } from './routes/r.$slug'
import { Route as DashboardStorefrontRouteImport } from './routes/dashboard.storefront'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard.settings'
import { Route as DashboardPaymentsRouteImport } from './routes/dashboard.payments'
import { Route as DashboardOrdersRouteImport } from './routes/dashboard.orders'
import { Route as DashboardMenuRouteImport } from './routes/dashboard.menu'
import { Route as DashboardCustomersRouteImport } from './routes/dashboard.customers'
import { Route as DashboardCampaignsRouteImport } from './routes/dashboard.campaigns'
import { Route as AdminIdRouteImport } from './routes/admin.$id'
import { Route as RSlugIndexRouteImport } from './routes/r.$slug.index'
import { Route as RSlugSuccessRouteImport } from './routes/r.$slug.success'
import { Route as RSlugMenuRouteImport } from './routes/r.$slug.menu'
import { Route as RSlugContactRouteImport } from './routes/r.$slug.contact'
import { Route as RSlugCheckoutRouteImport } from './routes/r.$slug.checkout'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const RSlugRoute = RSlugRouteImport.update({
  id: '/r/$slug',
  path: '/r/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStorefrontRoute = DashboardStorefrontRouteImport.update({
  id: '/storefront',
  path: '/storefront',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPaymentsRoute = DashboardPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardOrdersRoute = DashboardOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardMenuRoute = DashboardMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCustomersRoute = DashboardCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCampaignsRoute = DashboardCampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIdRoute = AdminIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRoute,
} as any)
const RSlugIndexRoute = RSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugSuccessRoute = RSlugSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugMenuRoute = RSlugMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugContactRoute = RSlugContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => RSlugRoute,
} as any)
const RSlugCheckoutRoute = RSlugCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => RSlugRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/$id': typeof AdminIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storefront': typeof DashboardStorefrontRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/r/$slug/checkout': typeof RSlugCheckoutRoute
  '/r/$slug/contact': typeof RSlugContactRoute
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/success': typeof RSlugSuccessRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/$id': typeof AdminIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storefront': typeof DashboardStorefrontRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/r/$slug/checkout': typeof RSlugCheckoutRoute
  '/r/$slug/contact': typeof RSlugContactRoute
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/success': typeof RSlugSuccessRoute
  '/r/$slug': typeof RSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/signup': typeof SignupRoute
  '/admin/$id': typeof AdminIdRoute
  '/dashboard/campaigns': typeof DashboardCampaignsRoute
  '/dashboard/customers': typeof DashboardCustomersRoute
  '/dashboard/menu': typeof DashboardMenuRoute
  '/dashboard/orders': typeof DashboardOrdersRoute
  '/dashboard/payments': typeof DashboardPaymentsRoute
  '/dashboard/settings': typeof DashboardSettingsRoute
  '/dashboard/storefront': typeof DashboardStorefrontRoute
  '/r/$slug': typeof RSlugRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/r/$slug/checkout': typeof RSlugCheckoutRoute
  '/r/$slug/contact': typeof RSlugContactRoute
  '/r/$slug/menu': typeof RSlugMenuRoute
  '/r/$slug/success': typeof RSlugSuccessRoute
  '/r/$slug/': typeof RSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/$id'
    | '/dashboard/campaigns'
    | '/dashboard/customers'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/r/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/r/$slug/checkout'
    | '/r/$slug/contact'
    | '/r/$slug/menu'
    | '/r/$slug/success'
    | '/r/$slug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/$id'
    | '/dashboard/campaigns'
    | '/dashboard/customers'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/admin'
    | '/dashboard'
    | '/r/$slug/checkout'
    | '/r/$slug/contact'
    | '/r/$slug/menu'
    | '/r/$slug/success'
    | '/r/$slug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/signup'
    | '/admin/$id'
    | '/dashboard/campaigns'
    | '/dashboard/customers'
    | '/dashboard/menu'
    | '/dashboard/orders'
    | '/dashboard/payments'
    | '/dashboard/settings'
    | '/dashboard/storefront'
    | '/r/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/r/$slug/checkout'
    | '/r/$slug/contact'
    | '/r/$slug/menu'
    | '/r/$slug/success'
    | '/r/$slug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  SignupRoute: typeof SignupRoute
  RSlugRoute: typeof RSlugRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$slug': {
      id: '/r/$slug'
      path: '/r/$slug'
      fullPath: '/r/$slug'
      preLoaderRoute: typeof RSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/storefront': {
      id: '/dashboard/storefront'
      path: '/storefront'
      fullPath: '/dashboard/storefront'
      preLoaderRoute: typeof DashboardStorefrontRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/payments': {
      id: '/dashboard/payments'
      path: '/payments'
      fullPath: '/dashboard/payments'
      preLoaderRoute: typeof DashboardPaymentsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/orders': {
      id: '/dashboard/orders'
      path: '/orders'
      fullPath: '/dashboard/orders'
      preLoaderRoute: typeof DashboardOrdersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/menu': {
      id: '/dashboard/menu'
      path: '/menu'
      fullPath: '/dashboard/menu'
      preLoaderRoute: typeof DashboardMenuRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/customers': {
      id: '/dashboard/customers'
      path: '/customers'
      fullPath: '/dashboard/customers'
      preLoaderRoute: typeof DashboardCustomersRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/campaigns': {
      id: '/dashboard/campaigns'
      path: '/campaigns'
      fullPath: '/dashboard/campaigns'
      preLoaderRoute: typeof DashboardCampaignsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/$id': {
      id: '/admin/$id'
      path: '/$id'
      fullPath: '/admin/$id'
      preLoaderRoute: typeof AdminIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/r/$slug/': {
      id: '/r/$slug/'
      path: '/'
      fullPath: '/r/$slug/'
      preLoaderRoute: typeof RSlugIndexRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/success': {
      id: '/r/$slug/success'
      path: '/success'
      fullPath: '/r/$slug/success'
      preLoaderRoute: typeof RSlugSuccessRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/menu': {
      id: '/r/$slug/menu'
      path: '/menu'
      fullPath: '/r/$slug/menu'
      preLoaderRoute: typeof RSlugMenuRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/contact': {
      id: '/r/$slug/contact'
      path: '/contact'
      fullPath: '/r/$slug/contact'
      preLoaderRoute: typeof RSlugContactRouteImport
      parentRoute: typeof RSlugRoute
    }
    '/r/$slug/checkout': {
      id: '/r/$slug/checkout'
      path: '/checkout'
      fullPath: '/r/$slug/checkout'
      preLoaderRoute: typeof RSlugCheckoutRouteImport
      parentRoute: typeof RSlugRoute
    }
  }
}

interface AdminRouteChildren {
  AdminIdRoute: typeof AdminIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminIdRoute: AdminIdRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardRouteChildren {
  DashboardCampaignsRoute: typeof DashboardCampaignsRoute
  DashboardCustomersRoute: typeof DashboardCustomersRoute
  DashboardMenuRoute: typeof DashboardMenuRoute
  DashboardOrdersRoute: typeof DashboardOrdersRoute
  DashboardPaymentsRoute: typeof DashboardPaymentsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRoute
  DashboardStorefrontRoute: typeof DashboardStorefrontRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCampaignsRoute: DashboardCampaignsRoute,
  DashboardCustomersRoute: DashboardCustomersRoute,
  DashboardMenuRoute: DashboardMenuRoute,
  DashboardOrdersRoute: DashboardOrdersRoute,
  DashboardPaymentsRoute: DashboardPaymentsRoute,
  DashboardSettingsRoute: DashboardSettingsRoute,
  DashboardStorefrontRoute: DashboardStorefrontRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface RSlugRouteChildren {
  RSlugCheckoutRoute: typeof RSlugCheckoutRoute
  RSlugContactRoute: typeof RSlugContactRoute
  RSlugMenuRoute: typeof RSlugMenuRoute
  RSlugSuccessRoute: typeof RSlugSuccessRoute
  RSlugIndexRoute: typeof RSlugIndexRoute
}

const RSlugRouteChildren: RSlugRouteChildren = {
  RSlugCheckoutRoute: RSlugCheckoutRoute,
  RSlugContactRoute: RSlugContactRoute,
  RSlugMenuRoute: RSlugMenuRoute,
  RSlugSuccessRoute: RSlugSuccessRoute,
  RSlugIndexRoute: RSlugIndexRoute,
}

const RSlugRouteWithChildren = RSlugRoute._addFileChildren(RSlugRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  SignupRoute: SignupRoute,
  RSlugRoute: RSlugRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
